// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Dlcodepen() {
    driver.Navigate().GoToUrl("https://codepen.io/danedens/full/ZExrjqV");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.SwitchTo().Frame(0);
    driver.FindElement(By.CssSelector(".contOut:nth-child(3) .fa")).Click();
    driver.FindElement(By.CssSelector(".contOut:nth-child(4) .fa")).Click();
    driver.FindElement(By.CssSelector(".fa-plus")).Click();
    
  }
}
